sudo: false

language: erlang
otp_release: 18.3

branches:
    only:
        - master

addons:
    apt:
        packages:
            - libexpat1-dev

install: make compile
script: make test

cache:
    directories:
        - dialyzer
